### ISSUE TITLE
Large vectors don't work

### ISSUE THREAD

**Issue by adefazio** [Rcpp11/Rcpp11#227]
If I run the following, examining the returned vector in R shows it's length to be 705032704 instead of 5 billion:

    // [[export]]
    NumericVector vout() {
        R_xlen_t nl = 5000000000.0;
        NumericVector v(nl);
        return v;
    }

Using 500 million instead of 5 billion gives the expected length when examined in R.

**Comment by romainfrancois** [comment]
Hmm that's odd. I'll check later but perhaps it is about the .0, perhaps it gets convertee to a double

**Comment by thirdwing** [comment]
Maybe because of these lines https://github.com/Rcpp11/Rcpp11/blob/master/inst/include/Rcpp/vector/impl/RCPP_VECTOR_API.h#L106-L108
